<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <classAccesses>
        <apexClass>APTSCU_ApprovalActionsController</apexClass>
        <enabled>true</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>APTS_CustomActionCallback_Test</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>APTS_CustomAgreementLCCallbackTestclass</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AccountContactRelationTriggerHandler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AccreditationHelper</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AccreditationLevelChangeScheduler</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AccreditationLevelChangeSchedulerTest</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AddKeyUserToPGQueue</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <classAccesses>
        <apexClass>AppConstants</apexClass>
        <enabled>false</enabled>
    </classAccesses>
    <custom>true</custom>
    <layoutAssignments>
        <layout>Change_Impact__c-Change Impact Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>ChannelProgramLevel-Channel Program Level Layout</layout>
    </layoutAssignments>
    <pageAccesses>
        <apexPage>InMaintenance</apexPage>
        <enabled>false</enabled>
    </pageAccesses>
</Profile>
