trigger AOP_insertvertical on AOP_For_Sales_Manger__c (after insert) {
List<AOP_For_Sales_Manger__c> aopsm = Trigger.new;
List<Field_Name__c> fnlst = new List<Field_Name__c>();
for(integer i=0;i<aopsm.size();i++)
{
   Field_Name__c fn1 = new Field_Name__c();
   fn1.ASMName__c = aopsm[i].Id;
   fn1.Field_Name__c='Opp_Closed_Won_Amount_for_RMU__c';
   fn1.Data_Sequence__c = 'Z';
   fn1.Grouping_2__c = 'Y';
   fn1.name = 'Closed Won';
   fnlst.add(fn1);
   Field_Name__c fn2 = new Field_Name__c();
   fn2.ASMName__c = aopsm[i].Id;
   fn2.Field_Name__c='Pipeline_BGA_AM__c';
   fn2.Data_Sequence__c = 'Z';
   fn2.Grouping_2__c = 'Y';
   fn2.name = 'BGA AM Total Revenue';
   fnlst.add(fn2);
   Field_Name__c fn3 = new Field_Name__c();
   fn3.ASMName__c = aopsm[i].Id;
   fn3.Field_Name__c='Pipeline_BGA_AM_Factored__c';
   fn3.Data_Sequence__c = 'Z';
   fn3.Grouping_2__c = 'Y';
   fn3.name ='BGA AM Factored Revenue' ;
    fnlst.add(fn3);
   Field_Name__c fn4 = new Field_Name__c();
   fn4.ASMName__c = aopsm[i].Id;
   fn4.Field_Name__c='Pipeline_RMU__c';
   fn4.Data_Sequence__c = 'BGA Total';
   fn4.Grouping_2__c = 'Y';
   fn4.name = 'RMU Total Revenue';
   fnlst.add(fn4);
   Field_Name__c fn5 = new Field_Name__c();
   fn5.ASMName__c = aopsm[i].Id;
   fn5.Field_Name__c='Pipeline_RMU_Factored__c';
   fn5.Data_Sequence__c = 'BGA Factored';
   fn5.Grouping_2__c ='Y';
   fn5.name ='RMU Factored Revenue' ;
   fnlst.add(fn5);
   Field_Name__c fn6 = new Field_Name__c();
   fn6.ASMName__c = aopsm[i].Id;
   fn6.Field_Name__c='AOP_BGA_AM__c';
   fn6.Data_Sequence__c = 'Z';
   fn6.Grouping_2__c = 'Y';
   fn6.name ='AOP BGA' ;
    fnlst.add(fn6);
   
   Field_Name__c fn7 = new Field_Name__c();
   fn7.ASMName__c = aopsm[i].Id;
   fn7.Field_Name__c='Actual_BGA_AM__c';
   fn7.Data_Sequence__c = 'BGA AM Closed Won';
   fn7.Grouping_2__c = 'BGA AM Actual + Pending';
   fn7.name = 'Closed Won';
   fnlst.add(fn7);
   Field_Name__c fn8 = new Field_Name__c();
   fn8.ASMName__c = aopsm[i].Id;
   fn8.Field_Name__c='AOP_RMU__c';
   fn8.Data_Sequence__c ='Z';
   fn8.Grouping_2__c = 'Y';
   fn8.name = 'AOP RMU';
    fnlst.add(fn8);
   Field_Name__c fn9 = new Field_Name__c();
   fn9.ASMName__c = aopsm[i].Id;
   fn9.Field_Name__c='Balance_AOP__c';
   fn9.Data_Sequence__c ='BGA AM Balance';
   fn9.Grouping_2__c = 'BGA AM Actual + Pending';
   fn9.name = 'Remaining AOP';
   fnlst.add(fn9);
   Field_Name__c fn10 = new Field_Name__c();
   fn10.ASMName__c = aopsm[i].Id;
   fn10.Field_Name__c='Balance_RMU_AOP__c';
   fn10.Data_Sequence__c ='Z';
   fn10.Grouping_2__c ='Y';
   fn10.name = 'Remaining AOP RMU';
   fnlst.add(fn10);
   Field_Name__c fn11 = new Field_Name__c();
   fn11.ASMName__c = aopsm[i].Id;
   fn11.Field_Name__c='Dealer_Amount__c';
   fn11.Data_Sequence__c = 'BGA Total';
   fn11.Grouping_2__c = 'Y' ;
   fn11.name = 'Dealer Total Amount';
    fnlst.add(fn11);
   Field_Name__c fn12 = new Field_Name__c();
   fn12.ASMName__c = aopsm[i].Id;
   fn12.Field_Name__c='Dealer_Factored__c';
   fn12.Data_Sequence__c ='BGA Factored';
   fn12.Grouping_2__c = 'Y';
   fn12.name = 'Dealer Factored';
   fnlst.add(fn12);
}
if(fnlst.size()>0)
insert fnlst;
}