/****************************************************
 * @Description: Test Class for unit code coverage
 * *************************************************/
@isTest(seeAllData = false)
public with Sharing class SPoG_InterfaceHelperTest {
    
    /*******************************************
     * @Description: Test method for callout interfaces. 
     * Run all SPoG_ Test Class to get full coverage
     * ****************************************/
    testmethod static void testInterface() {
        SPoG_InterfaceHelper objHelper = new SPoG_InterfaceHelper(); 
    }

}