public class TriggerCheck 
{ 
   public static boolean firstRun = true; 
   public static boolean firstAtrRun = true; 
   public static boolean firstIntEscRun = true; 
   public static boolean firstOwnerChange = true; 
   public static boolean ACSMMailsend = true;
   public static boolean MyMaintainerChange = true;
   public static boolean EmailTempcheck = true;
   public static boolean avoidRecursionROI = TRUE;
}