/** * File Name: UpdatePrimary_ApexClass4
* Description Test Method
* Copyright : Wipro Technologies Limited Copyright (c) 2010
* * @author : Wipro
* Modification Log =============================================================== 
Ver Date Author Modification --- ---- ------ -------------
* */ 
@isTest
private  class UpdatePrimary_ApexClass4 {
static testmethod void testUpdatePrimary(){

 //creating account;
 /*Account acc= new Account(name='Test Account');
 insert acc;
 
 //creating contact;
 Contact cont=new Contact(firstname='Test',LastName='Contact',AccountId=acc.Id,Phone_3__c='9986502495',
  Contact_Is_Employee__c=true,  Contact_Status__c='Active', Employee_Contact_Role__c='Analyst',Employee_Number__c='567' );
 insert cont;


Skills2__c skill= new Skills2__c (Primary_Secondary__c='Primary' ,Supported_Product__c='Radio',   Contact__c=cont.Id);
insert skill;

test.starttest();
Case cases14=new Case(AccountId=acc.Id,subject='Fax:{9986502495} test data',ContactId=cont.Id,Export_Compliance_Content_ITAR_EAR__c='No', Government_Compliance_SM_M_Content__c='No',
No_FCR_Reason__c='Not Trained',Type='Order',
//Supported_Product__c='Radio',Origin ='Email-GBS-AES-Repair'); -- Commented for INC000006656211
Supported_Product__c='Radio',Origin ='Email-R&O Avionics');
insert cases14;
test.stoptest();*/
 }

}